DROP TABLE PRODUCT CASCADE CONSTRAINTS;

CREATE TABLE PRODUCT (
    PRODUCT_ID VARCHAR2(30) CONSTRAINT PK_PRODUCT PRIMARY KEY,
    P_NAME VARCHAR2(30) NOT NULL,
    PRICE NUMBER NOT NULL,
    DESCRIPTION VARCHAR2(30)
);

COMMENT ON COLUMN  PRODUCT.PRODUCT_ID IS '제품번호';
COMMENT ON COLUMN  PRODUCT.P_NAME IS '제품이름';
COMMENT ON COLUMN  PRODUCT.PRICE IS '제품가격';
COMMENT ON COLUMN  PRODUCT.DESCRIPTION IS '설명';

INSERT INTO PRODUCT VALUES ('nb_ss7', '삼성노트북', 1570000, '시리즈 7');
INSERT INTO PRODUCT VALUES ('nb_ama4', '맥북에어', 1200000, 'xcode 4');
INSERT INTO PRODUCT VALUES ('pc_ibm', 'ibmPC', 750000,	'windows8');

COMMIT;